export const SET_MATRIX = "SET_MATRIX";
export const INCREMENT_VALUE = "INCREMENT_VALUE";
export const SHOW_PERCENT_ACTION = "SHOW_PERCENT_ACTION";
export const SHOW_CLOSE_ACTION = "SHOW_CLOSE_ACTION";
export const ADD_ROW_ACTION = "ADD_ROW_ACTION";
export const DELETE_ROW_ACTION = "DELETE_ROW_ACTION";
